app-id: com.sshconfigstudio.app
runtime: org.gnome.Platform
runtime-version: '47'
sdk: org.gnome.Sdk
command: ssh-config-studio
finish-args:
  # GUI + portals
  - --share=ipc
  - --socket=fallback-x11
  - --socket=wayland
  # Networking for ssh
  - --share=network
  # Access to user's SSH config and keys (read/write)
  - --filesystem=~/.ssh:rw
  # Access to SSH agent inside the sandbox
  - --socket=ssh-auth
modules:
  - name: blueprint-compiler
    buildsystem: meson
    config-opts:
      - --prefix=/app
    sources:
      - type: git
        url: https://gitlab.gnome.org/jwestman/blueprint-compiler.git
        tag: v0.18.0
  - name: ssh-config-studio
    buildsystem: meson
    sources:
      - type: dir
        path: .
    post-install:
      - |
        printf '#!/usr/bin/env bash\nexec python3 -m ssh_config_studio.main "$@"\n' > /app/bin/ssh-config-studio
      - chmod +x /app/bin/ssh-config-studio
    cleanup:
      - /include
      - /lib/pkgconfig
      - /share/man
      - /share/pkgconfig
      - /share/gtk-doc
      - /share/doc
      - /share/devhelp

