name: Build AppImage (Linux)

on:
  push:
    branches: [ master ]
    tags: [ 'v*', '*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  appimage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies and appimage-builder
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            squashfs-tools zsync desktop-file-utils appstream file patchelf libglib2.0-bin fakeroot
          python -m pip install --upgrade pip
          python -m pip install --user "appimage-builder==0.8.2"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SSH-Studio-AppImage
          path: '*.AppImage'

      - name: Publish Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.AppImage
            *.zsync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

