name: Build AppImage (Linux)

on:
  push:
    branches: [ master ]
    tags: [ 'v*', '*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  appimage:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install AppImage Builder
        run: |
          sudo add-apt-repository -y ppa:appimagebuilder-team/stable
          sudo apt-get update
          sudo apt-get install -y appimage-builder

      - name: Build AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SSH-Studio-AppImage
          path: '*.AppImage'

      - name: Publish Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.AppImage
            *.zsync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

